# Enhanced Proxy Tester Configuration
# This file contains all configuration options for the enhanced proxy testing system

# Proxy Tester Configuration
proxy_tester:
  # Maximum number of concurrent workers for testing
  max_workers: 300

  # Timeout for each proxy test
  timeout: 5s

  # Number of configurations to test in each batch
  batch_size: 300

  # Path to Xray executable (auto-detected if empty)
  xray_path: "./xray.exe"

  # Enable incremental saving of working configurations
  incremental_save: true

  # Port range for proxy testing
  port_range:
    start: 10000
    end: 20000

  # Smart retry configuration
  retry:
    max_retries: 3
    base_delay: 1s
    max_delay: 30s
    backoff_factor: 2.0
    enable_jitter: true

# Quality Tester Configuration  
quality_tester:
  # Maximum number of configurations to test for quality
  max_configs: 10000

  # Number of concurrent quality tests
  concurrent: 8

  # Timeout for quality testing
  test_timeout: 120s

  # Minimum stability threshold (0.0-1.0)
  stability_threshold: 0.75

  # Enable adaptive testing (adjusts based on performance)
  adaptive_testing: true

  # Scoring weights (must sum to ~1.0)
  critical_site_weight: 0.50  # Weight for critical sites (filtered in Iran)
  latency_weight: 0.25        # Weight for connection quality/latency
  stability_weight: 0.15      # Weight for connection stability
  speed_weight: 0.10          # Weight for connection speed

# Common Configuration
common:
  # Output directory for results
  output_dir: "../data"

  # Temporary directory for config files
  temp_dir: "./temp"

  # Maximum file size (bytes)
  max_file_size: 104857600  # 100MB

  # Cleanup files after this duration
  cleanup_after: 1h

  # Enable metrics collection and reporting
  enable_metrics: true

# Logging Configuration
logging:
  # Log level: debug, info, warn, error, fatal
  level: "info"

  # Log format: text or json
  format: "text"

  # Log output file (empty for stdout only)
  output_file: ""

  # Maximum log file size in MB
  max_size: 100

  # Maximum number of backup files
  max_backups: 3

  # Maximum age of log files in days
  max_age: 28

  # Compress old log files
  compress: true

# Performance Optimization Configuration
performance:
  # Enable HTTP connection pooling
  enable_connection_pool: true

  # HTTP connection pool size
  pool_size: 100

  # Pool timeout
  pool_timeout: 30s

  # Enable circuit breaker pattern
  enable_circuit_breaker: true

  # Circuit breaker configuration
  circuit_breaker:
    # Maximum failures before opening circuit
    max_failures: 5

    # Timeout before trying to close circuit
    timeout: 60s

    # Reset timeout for half-open state
    reset_timeout: 30s

    # Failure rate threshold (0.0-1.0)
    threshold_rate: 0.5

  # Rate limiting configuration
  rate_limit:
    # Enable rate limiting
    enabled: true

    # Maximum requests per second
    requests_per_sec: 10

    # Burst size for rate limiter
    burst_size: 20

    # Cleanup period for rate limiter
    cleanup_period: 1m

  # Memory optimization settings
  memory_optimization:
    # Enable buffer pooling
    enable_buffer_pool: true

    # Buffer size in bytes
    buffer_size: 32768  # 32KB

    # Maximum number of buffers in pool
    max_buffers: 1000

    # Enable garbage collection optimization
    enable_gc_optimization: true

    # GC target percentage
    gc_percent: 100
