name: Automated Proxy Collection and Testing

on:
  schedule:
    # Run every 12 hours at 00:00 and 12:00 UTC
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  actions: read

jobs:
  proxy-collection-and-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        echo "Installing required Python packages..."
        pip install tenacity requests
        echo "Python dependencies installed successfully"

    - name: Set up Go 1.25.1
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Install Go dependencies
      run: |
        cd xray_test
        go mod download
        go mod verify

    - name: Clear data folder
      run: |
        echo "Clearing data folder..."
        if [ -d "data" ]; then
          rm -rf data/*
          echo "Data folder cleared successfully"
        else
          mkdir -p data
          echo "Data folder created"
        fi

    - name: Execute Python proxy collector
      id: python-collector
      run: |
        echo "Starting Python proxy collection..."
        cd config_collector
        python main.py
        echo "Python proxy collection completed"
      continue-on-error: true

    - name: Check Python collector results
      run: |
        if [ "${{ steps.python-collector.outcome }}" = "failure" ]; then
          echo "⚠️ Python collector failed, but continuing with Go tests"
        else
          echo "✅ Python collector completed successfully"
        fi

    - name: Execute Go proxy tester
      id: go-proxy-tester
      run: |
        echo "Starting Go proxy connectivity testing..."
        cd xray_test
        timeout 300 go run proxy-tester.go || echo "Proxy tester completed (may have timed out)"
        echo "Go proxy testing completed"
      continue-on-error: true

    - name: Execute Go quality tester
      id: go-quality-tester
      run: |
        echo "Starting Go proxy quality testing..."
        cd xray_test
        timeout 300 go run quality_tester.go || echo "Quality tester completed (may have timed out)"
        echo "Go quality testing completed"
      continue-on-error: true

    - name: Execute Go speed tester
      id: go-speed-tester
      run: |
        echo "Starting Go proxy speed testing..."
        cd xray_test
        timeout 300 go run speed_tester.go || echo "Speed tester completed (may have timed out)"
        echo "Go speed testing completed"
      continue-on-error: true

    - name: Check data folder contents
      run: |
        echo "Checking data folder contents..."
        if [ -d "data" ]; then
          echo "=== Full directory structure ==="
          find data -type f -name "*" | head -50
          echo "=== File counts by type ==="
          echo "Working JSON: $(find data/working_json -type f 2>/dev/null | wc -l || echo 0)"
          echo "Working URL: $(find data/working_url -type f 2>/dev/null | wc -l || echo 0)"
          echo "Quality results: $(find data/quality_results -type f 2>/dev/null | wc -l || echo 0)"
          echo "Speed results: $(find data/speed_results -type f 2>/dev/null | wc -l || echo 0)"
          echo "Total files: $(find data -type f | wc -l)"
        else
          echo "Data folder not found"
        fi

    - name: Configure git for automated commits
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        echo "Checking for changes..."
        git add data/

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          echo "Changes detected, committing..."

          # Create commit message with execution summary
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          PYTHON_STATUS="${{ steps.python-collector.outcome }}"
          PROXY_STATUS="${{ steps.go-proxy-tester.outcome }}"
          QUALITY_STATUS="${{ steps.go-quality-tester.outcome }}"
          SPEED_STATUS="${{ steps.go-speed-tester.outcome }}"
          RUN_ID="${{ github.run_id }}"
          GITHUB_REF_NAME="${{ github.ref_name }}"

          git commit -m "Automated proxy collection - ${TIMESTAMP}" \
                     -m "Python Collector: ${PYTHON_STATUS}" \
                     -m "Proxy Tester: ${PROXY_STATUS}" \
                     -m "Quality Tester: ${QUALITY_STATUS}" \
                     -m "Speed Tester: ${SPEED_STATUS}" \
                     -m "Workflow run: ${RUN_ID}"
          git push origin "${GITHUB_REF_NAME}"
          echo "✅ Changes committed and pushed successfully"
        fi

    - name: Upload all results as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: proxy-results-${{ github.run_id }}
        path: |
          data/working_json/
          data/working_url/
          data/quality_results/
          data/speed_results/
        retention-days: 7

    - name: Upload individual artifact for each result type
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: working-json-${{ github.run_id }}
        path: data/working_json/
        retention-days: 7

    - name: Upload working URLs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: working-urls-${{ github.run_id }}
        path: data/working_url/
        retention-days: 7

    - name: Upload quality results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: quality-results-${{ github.run_id }}
        path: data/quality_results/
        retention-days: 7

    - name: Upload speed results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: speed-results-${{ github.run_id }}
        path: data/speed_results/
        retention-days: 7

    - name: Workflow summary
      if: always()
      run: |
        echo "## 🤖 Automated Proxy Collection Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Execution Time:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "**Workflow Run:** [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Script Execution Status" >> $GITHUB_STEP_SUMMARY
        echo "| Script | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Python Collector | ${{ steps.python-collector.outcome == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Go Proxy Tester | ${{ steps.go-proxy-tester.outcome == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Go Quality Tester | ${{ steps.go-quality-tester.outcome == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Go Speed Tester | ${{ steps.go-speed-tester.outcome == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ -d "data" ]; then
          echo "### Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Result Type | File Count |" >> $GITHUB_STEP_SUMMARY
          echo "|-------------|------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Working JSON | $(find data/working_json -type f 2>/dev/null | wc -l || echo 0) |" >> $GITHUB_STEP_SUMMARY
          echo "| Working URLs | $(find data/working_url -type f 2>/dev/null | wc -l || echo 0) |" >> $GITHUB_STEP_SUMMARY
          echo "| Quality Results | $(find data/quality_results -type f 2>/dev/null | wc -l || echo 0) |" >> $GITHUB_STEP_SUMMARY
          echo "| Speed Results | $(find data/speed_results -type f 2>/dev/null | wc -l || echo 0) |" >> $GITHUB_STEP_SUMMARY
          echo "| **Total Files** | **$(find data -type f | wc -l)** |" >> $GITHUB_STEP_SUMMARY
        else
          echo "**Data Files Generated:** 0" >> $GITHUB_STEP_SUMMARY
        fi
